name: adjustin_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_signin_button: ^1.1.0
  state_notifier: ^0.6.0
  flutter_riverpod: ^0.9.1
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  flutter_state_notifier: ^0.6.1
  freezed_annotation:
  pedantic_mono: ^1.10.0+2
  analyzer: 0.39.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  build_runner:


flutter:
  uses-material-design: true
